In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/home/alvaro/tf_templates/DATA/Top-Largest-Universities.csv')

In [3]:
df.head()

,Rank,Institution,Location,Continent,Founded,Affiliation,Distance / In-Person,Enrollment
0,1,Indira Gandhi National Open University,"New Delhi, India",Asia,1985,Public,Distance/In-Person,7140000
1,2,California Community Colleges System,"California, United States",North America,1967,Public,In-Person,2133846
2,3,"National University, Bangladesh","Gazipur, Bangladesh",Asia,1992,Public,In-Person,2097182
3,4,Anadolu University,"Eskişehir, Turkey",Asia,1958,Public,Distance/In-Person,1974343
4,5,Allama Iqbal Open University,"Islamabad, Pakistan",Asia,1974,Public,Distance/In-Person,1027000

In [4]:
df.groupby('Founded')

In [5]:
df.groupby('Continent').min()

,Rank,Institution,Location,Founded,Affiliation,Distance / In-Person,Enrollment
Continent,,,,,,,
Africa,17,Ain Shams University,"Cairo, Egypt",1873,Public,Distance,170000
Asia,1,Indira Gandhi National Open University,"Bangkok, Thailand",1857,Private,Distance,60000
Europe,33,Complutense University of Madrid,"Belgrade, Serbia",1293,Private,Distance,76096
Global,7,"Laureate Education, Inc.",International,1999,Private,Distance/In-Person,875000
North America,2,Autonomous University of Santo Domingo,"California, United States",1538,Private,Distance,88766
South America,29,Estácio de Sá University,"Buenos Aires, Argentina",1613,Private,Distance/In-Person,113558

In [6]:
df.groupby(['Continent','Affiliation']).min()

                           Rank  \
Continent     Affiliation
Africa        Public         17
Asia          Private         6
              Public          1
Europe        Private        75
              Public         33
Global        Private         7
North America Private        53
              Public          2
South America Private        38
              Public         29

                                                                 Institution  \
Continent     Affiliation
Africa        Public                                    Ain Shams University
Asia          Private       Academic Center for Education, Culture and Re...
              Public                  Indira Gandhi National Open University
Europe        Private        IU International University of Applied Sciences
              Public                        Complutense University of Madrid
Global        Private                               Laureate Education, Inc.
North America Private                                     Liberty University
              Public                  Autonomous University of Santo Domingo
South America Private                               Estácio de Sá University
              Public                          National University of Córdoba

                                            Location Founded  \
Continent     Affiliation
Africa        Public                    Cairo, Egypt    1873
Asia          Private                           Iran    1980
              Public               Bangkok, Thailand    1857
Europe        Private                Erfurt, Germany    1998
              Public                Belgrade, Serbia    1293
Global        Private                  International    1999
North America Private      California, United States    1932
              Public       California, United States    1538
South America Private                       Colombia    1970
              Public         Buenos Aires, Argentina    1613

                          Distance / In-Person  Enrollment
Continent     Affiliation
Africa        Public                  Distance      170000
Asia          Private                In-Person       60000
              Public                  Distance       80000
Europe        Private       Distance/In-Person      100000
              Public                  Distance       76096
Global        Private       Distance/In-Person      875000
North America Private                 Distance       91200
              Public                 In-Person       88766
South America Private       Distance/In-Person      116782
              Public                 In-Person      113558

In [7]:
df.groupby('Continent').describe().transpose()

Continent                Africa          Asia         Europe    Global  \
Rank       count       4.000000  3.100000e+01      11.000000       1.0
           mean       31.250000  3.280645e+01      63.000000       7.0
           std        15.195942  2.560263e+01      17.714401       NaN
           min        17.000000  1.000000e+00      33.000000       7.0
           25%        20.750000  1.250000e+01      48.500000       7.0
           50%        28.500000  2.400000e+01      67.000000       7.0
           75%        39.000000  5.250000e+01      77.500000       7.0
           max        51.000000  8.400000e+01      83.000000       7.0
Enrollment count       4.000000  3.100000e+01      11.000000       1.0
           mean   340550.000000  7.021327e+05  139182.363636  875000.0
           std    155755.823861  1.289412e+06   58901.765404       NaN
           min    170000.000000  6.000000e+04   76096.000000  875000.0
           25%    235400.000000  1.674785e+05   94705.500000  875000.0
           50%    338600.000000  4.000000e+05  120000.000000  875000.0
           75%    443750.000000  6.254520e+05  175000.000000  875000.0
           max    515000.000000  7.140000e+06  260079.000000  875000.0

Continent         North America  South America
Rank       count   3.100000e+01       6.000000
           mean    4.503226e+01      55.333333
           std     2.152283e+01      17.339742
           min     2.000000e+00      29.000000
           25%     2.900000e+01      44.250000
           50%     4.400000e+01      63.500000
           75%     6.350000e+01      67.000000
           max     8.000000e+01      70.000000
Enrollment count   3.100000e+01       6.000000
           mean    2.992213e+05  172583.000000
           std     3.701734e+05   79503.234800
           min     8.876600e+04  113558.000000
           25%     1.351815e+05  120086.500000
           50%     1.893510e+05  137054.000000
           75%     3.372785e+05  197277.000000
           max     2.133846e+06  316050.000000