In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pwd

'/content'

In [ ]:
ls

drive/  sample_data/  senoCopia.csv

In [ ]:
df = pd.read_csv('/content/drive/My Drive/DATA/Top-Largest-Universities.csv')
df

,Rank,Institution,Location,Continent,Founded,Affiliation,Distance / In-Person,Enrollment
0,1,Indira Gandhi National Open University,"New Delhi, India",Asia,1985,Public,Distance/In-Person,7140000
1,2,California Community Colleges System,"California, United States",North America,1967,Public,In-Person,2133846
2,3,"National University, Bangladesh","Gazipur, Bangladesh",Asia,1992,Public,In-Person,2097182
3,4,Anadolu University,"Eskişehir, Turkey",Asia,1958,Public,Distance/In-Person,1974343
4,5,Allama Iqbal Open University,"Islamabad, Pakistan",Asia,1974,Public,Distance/In-Person,1027000
...,...,...,...,...,...,...,...,...
79,80,University of Toronto,"Toronto, Canada",North America,1827,Public,In-Person,88766
80,81,Complutense University of Madrid,"Madrid, Spain",Europe,1293,Public,In-Person,83000
81,82,Farhangian University,Iran,Asia,2012,Public,In-Person,80000
82,83,University of Hagen,"Hagen, Germany",Europe,1974,Public,Distance,76096
83,84,"Academic Center for Education, Culture and Re...",Iran,Asia,1980,Private,In-Person,60000

In [ ]:
df.to_csv('/content/drive/My Drive/DATA/Top-Largest-Universities-COPY.csv',index=False)

In [ ]:
banks = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

In [ ]:
banks

[                         Bank NameBank       CityCity StateSt  CertCert  \
 0                        Citizens Bank       Sac City      IA      8758
 1             Heartland Tri-State Bank        Elkhart      KS     25851
 2                  First Republic Bank  San Francisco      CA     59017
 3                       Signature Bank       New York      NY     57053
 4                  Silicon Valley Bank    Santa Clara      CA     24735
 ..                                 ...            ...     ...       ...
 563                 Superior Bank, FSB       Hinsdale      IL     32646
 564                Malta National Bank          Malta      OH      6629
 565    First Alliance Bank & Trust Co.     Manchester      NH     34264
 566  National State Bank of Metropolis     Metropolis      IL      3815
 567                   Bank of Honolulu       Honolulu      HI     21029

                  Acquiring InstitutionAI Closing DateClosing  FundFund
 0              Iowa Trust & Savings Bank    November 3, 2023     10545
 1                 Dream First Bank, N.A.       July 28, 2023     10544
 2              JPMorgan Chase Bank, N.A.         May 1, 2023     10543
 3                    Flagstar Bank, N.A.      March 12, 2023     10540
 4    First–Citizens Bank & Trust Company      March 10, 2023     10539
 ..                                   ...                 ...       ...
 563                Superior Federal, FSB       July 27, 2001      6004
 564                    North Valley Bank         May 3, 2001      4648
 565  Southern New Hampshire Bank & Trust    February 2, 2001      4647
 566              Banterra Bank of Marion   December 14, 2000      4646
 567                   Bank of the Orient    October 13, 2000      4645

 [568 rows x 7 columns]]

In [ ]:
banks[0].head()

,Bank NameBank,CityCity,StateSt,CertCert,Acquiring InstitutionAI,Closing DateClosing,FundFund
0,Citizens Bank,Sac City,IA,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
1,Heartland Tri-State Bank,Elkhart,KS,25851,"Dream First Bank, N.A.","July 28, 2023",10544
2,First Republic Bank,San Francisco,CA,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
3,Signature Bank,New York,NY,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
4,Silicon Valley Bank,Santa Clara,CA,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539